# Generated by Django 4.2.29 on 2026-05-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_userprofile_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='estimated_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
