# Generated by Django 4.2.29 on 2026-05-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_stop_arrival_time_stop_departure_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='packingitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='packing_items/'),
        ),
        migrations.AddField(
            model_name='packingitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='packingitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
