# Generated by Django 4.2.29 on 2026-05-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_packingitem_description_packingitem_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingitem',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('documents', 'Documents'), ('electronics', 'Electronics'), ('toiletries', 'Toiletries'), ('medications', 'Medications'), ('food', 'Food/Snacks'), ('gear', 'Gear/Equipment'), ('entertainment', 'Entertainment'), ('gifts', 'Gifts/Souvenirs'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
