# Generated by Django 4.2.29 on 2026-05-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_packingitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual_spending',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
